###
GET http://localhost:8080/exam/java/add?question=Вопрос 1&answer=Ответ 1
###
GET http://localhost:8080/exam/java/add?question=Вопрос 2&answer=Ответ 2
###
GET http://localhost:8080/exam/java/add?question=Вопрос 3&answer=Ответ 3
###
GET http://localhost:8080/exam/java/add?question=Вопрос 4&answer=Ответ 4
###
GET http://localhost:8080/exam/java/add?question=Вопрос 5&answer=Ответ 5
###
GET http://localhost:8080/exam/java/add?question=Вопрос 6&answer=Ответ 6
###
GET http://localhost:8080/exam/java/add?question=Вопрос 7&answer=Ответ 7
###
GET http://localhost:8080/exam/java/add?question=Вопрос 8&answer=Ответ 8
###
GET http://localhost:8080/exam/java/add?question=Вопрос 9&answer=Ответ 9

###
GET http://localhost:8080/exam/java/remove?question=Вопрос 9&answer=Ответ 9

###
GET http://localhost:8080/exam/java

###
GET http://localhost:8080/exam/get/5